// Generated by CoffeeScript 1.3.3
/*   dCache for all devric plugins
*/

if (window.dCache === void 0) {
  window.dCache = {};
}

/* ===========================
  Plugin Class
==============================
*/


(function($, window) {
  /* Plugin class
  */

  var dTab;
  dTab = (function() {
    /* default elements
    ======================
    */

    function dTab(el, opts) {
      /* Assign
      */
      this.el = $(el);
      this.opts = opts;
      this.meta = this.el.data();
      this.id = this.el.attr('id');
      this.tabs = this.el.find('.tab');
    }

    dTab.prototype.log = function(msg) {
      if (this.opts.debug) {
        return typeof console !== "undefined" && console !== null ? console.log(msg) : void 0;
      }
    };

    /* plugin default options 
    ======================
    */


    dTab.prototype.defaults = {
      debug: false,
      fx: 'none',
      'lock': false,
      timer: false,
      inSpeed: false,
      outSpeed: false,
      speed: 250,
      trigger: 'click'
    };

    /* initiator
    ======================
    */


    dTab.prototype.init = function() {
      this.opts = $.extend({}, this.defaults, this.opts, this.meta);
      this.width = this.opts.width ? this.opts.width : this.util.getLargest(this.tabs, 'width');
      return this.height = this.opts.height ? this.opts.height : this.util.getLargest(this.tabs, 'height');
    };

    /*  builder
    =================
    */


    dTab.prototype.build = function(obj) {
      var i, menu, nav, title;
      this.el.prepend('<div class="container" />');
      /* Menu
      */

      menu = '<ul class="menu" />';
      if (this.opts['menu']) {
        this.el.append(menu);
      } else {
        this.el.prepend(menu);
      }
      title = this.tabs.find('.title');
      title.prependTo(this.el.find('.menu'));
      /* nav
      */

      nav = '<ul class="nav">';
      if (this.opts['navPosition']) {
        switch (this.opts['nav']) {
          case 'both':
            this.el.find('.container').before(nav);
            this.el.find('.container').after(nav);
            break;
          case 'bot':
            this.el.find('.container').after(nav);
        }
      } else {
        this.el.find('.container').before(nav);
      }
      /* Pager
      */

      if (this.opts['pager']) {
        i = this.tabs.length + 1;
        while (i -= 1) {
          this.el.find('.nav').prepend('<li class="pager">' + i + '</li>');
        }
      }
      if (this.opts['nav']) {
        this.el.find('.nav').prepend('<li class="prev">prev</li>');
        this.el.find('.nav').append('<li class="next">next</li>');
      }
      title.each(function() {
        return $(this).replaceWith('<li><span class="text">' + $(this).html() + '</span></li>');
      });
      this.tabs.prependTo(this.el.find('.container'));
      if (this.opts['lock'] || (this.opts['fx'] !== 'none' && this.opts['fx'] !== 'fade')) {
        this.el.find('.container').css({
          overflow: 'hidden',
          width: (obj['width'] ? obj['width'] : this.width),
          height: (obj['height'] ? obj['height'] : this.height)
        });
        this.tabs.css({
          overflow: 'hidden',
          width: (obj['width'] ? obj['width'] : this.width),
          height: (obj['height'] ? obj['height'] : this.height)
        });
      }
      if (this.opts['fx'] === 'none' || this.opts['fx'] === 'fade') {
        this.tabs.not(':first').css({
          display: 'none'
        });
      }
      this.el.find('.menu').children().first().addClass('active');
      this.el.find('.pager').first().addClass('active');
      return this.el.find('.prev').addClass('disable');
    };

    /* FX
    =================
    */


    dTab.prototype.fx = function(fx) {
      var effects, obj;
      obj = this;
      if (!fx) {
        fx = 'none';
      }
      effects = {
        none: function() {
          return obj.el.on('paging', function(evt, param) {
            obj.el.find('.tab').hide();
            return obj.el.find('.tab').eq(param['i']).show();
          });
        },
        fade: function() {
          return obj.el.on('paging', function(evt, param) {
            return obj.el.find('.tab').fadeOut(param['outSpeed']).promise().done(function() {
              return obj.el.find('.tab').eq(param['i']).fadeIn(param['inSpeed']);
            });
          });
        },
        slideX: function() {
          var totalWidth;
          totalWidth = obj.width * obj.tabs.length;
          obj.el.find('.container').wrapInner('<div class="js-tab-full-size" style="width: ' + totalWidth + 'px; height:' + obj.height + 'px" />');
          obj.tabs.css({
            float: 'left'
          });
          return obj.el.on('paging', function(evt, param) {
            return obj.el.find('.js-tab-full-size').animate({
              'margin-left': param['back'] + (param['diff'] * obj.width)
            });
          });
        },
        slideY: function() {
          var totalHeight;
          totalHeight = obj.height * obj.tabs.length;
          obj.el.find('.container').wrapInner('<div class="js-tab-full-size" style="width: ' + obj.width + 'px; height:' + totalHeight + 'px" />');
          return obj.el.on('paging', function(evt, param) {
            return obj.el.find('.js-tab-full-size').animate({
              'margin-top': param['back'] + (param['diff'] * obj.height)
            });
          });
        }
      };
      return effects[fx]();
    };

    /* utility
    =================
    */


    dTab.prototype.util = {
      findDiff: function() {
        var num;
        num = arguments[0] - arguments[1];
        return {
          diff: Math.abs(num),
          back: num < 0 ? '-=' : '+='
        };
      },
      setActive: function(el) {
        return $(el).addClass('active').siblings().removeClass('active');
      },
      setDisable: function() {},
      getLargest: function(el, d) {
        var size;
        size = [];
        el.each(function() {
          return size.push($(this)[d]());
        });
        return Math.max.apply(this, size);
      }
    };

    return dTab;

  })();
  /* == Exports =============
  */

  return dCache['dTab'] = dTab;
})(jQuery, window);

/* ===========================
  Jquery Plugin Interface
==============================
*/


(function($, window) {
  var pluginName;
  if (window.plugin === void 0) {
    window.plugin = {};
  }
  pluginName = 'devTab';
  plugin[pluginName] = '0.1.0Dead simple tabs with slideshows';
  plugin[pluginName + '_url'] = 'devric.co.cc';
  /* Adds plugin object to jQuery
  */

  return $.fn[pluginName] = function(options) {
    return this.each(function() {
      var D, self;
      self = $(this);
      /* Prevent re-initialize
      */

      if ($(this).hasClass('js-init')) {
        return false;
      }
      $(this).addClass('js-init');
      D = new dCache['dTab'](this, options);
      D.init();
      D.log(D);
      /* build it
      */

      D.build({
        width: D.opts.width,
        height: D.opts.height
      });
      /* Effects
          if no effects options, use default
      */

      if (D.opts.fx) {
        D.fx(D.opts.fx);
      } else {
        D.fx();
      }
      /* Trigger : menu
      */

      self.on(D.opts.trigger, '.menu li', function() {
        var diff;
        if ($(this).hasClass('active')) {
          return false;
        }
        diff = D.util.findDiff(self.find('.menu .active').index(), $(this).index());
        self.trigger('paging', {
          i: $(this).index(),
          inSpeed: !D.opts.inSpeed ? D.opts.speed : void 0,
          outSpeed: !D.opts.outSpeed ? D.opts.speed : void 0,
          diff: diff.diff,
          back: diff.back
        });
        D.util.setActive(this);
        D.util.setActive(self.find('.pager').eq($(this).index()));
        if (self.find('.menu .active').index() === 0) {
          self.find('.next, .prev').removeClass('disable');
          return self.find('.prev').addClass('disable');
        } else if (self.find('.menu .active').index() === self.find('.menu li').length - 1) {
          self.find('.next, .prev').removeClass('disable');
          return self.find('.next').addClass('disable');
        } else {
          return self.find('.next, .prev').removeClass('disable');
        }
      });
      /* Trigger : nav
      */

      self.on('click', '.prev', function() {
        if (self.find('.menu .active').index() !== 0) {
          return self.find('.menu .active').prev().trigger('click');
        }
      });
      self.on('click', '.next', function() {
        if (self.find('.menu .active').index() !== self.find('.menu li').length - 1) {
          return self.find('.menu .active').next().trigger('click');
        }
      });
      /* Trigger: pager
      */

      return self.on('click', '.pager', function() {
        return self.find('.menu li').eq($(this).index() - 1).trigger('click');
      });
    });
  };
})(jQuery, window);

/* ============== AUTO RUN DEFAULT =============
*/


/* =================================================
 Any new methods will require re-initiate the plugin
=================================================
*/


$(function() {
  return $('.dtab').devTab({
    debug: true
  });
});
